name: nina
favicon: null
layout_spectrum: 0.28479391476139426
typography_spectrum: 0.9130786736495793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7426801100373268
  lightness: 0.6955273919738829
  saturation: 0.5403216076083481
  rhythmicContrast: 0.04773626569658518
purpose: []
